dist:
  trusty

sudo:
 false

language:
  java

jdk:
  - oraclejdk8

install: mvn install -DskipTests -Dgpg.skip  -Dmaven.javadoc.skip=true -B -V

after_success:
  - mvn clean test jacoco:report coveralls:report
